//
// Created by Semyon Tikhonenko on 12/21/21.
//

#ifndef JNIBRIDGEGENERATOR_CUSTOMCONVERTERS_H
#define JNIBRIDGEGENERATOR_CUSTOMCONVERTERS_H

#include <jni.h>

#endif //JNIBRIDGEGENERATOR_CUSTOMCONVERTERS_H
